apiVersion: v1
kind: Service
metadata:
  name: {{app_name}}
  namespace: {{namespace}}
  labels:
    app.kubernetes.io/name: {{app_name}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{app_name}}
  ports:
    - port: {{service_port}}
      targetPort: {{port}}
      protocol: TCP
      name: http
